plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.kover)
}

android {
    namespace = "io.nemopill.scheduling"
    compileSdk = 35

    defaultConfig {
        minSdk = 26
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
        }
    }
}

dependencies {
    implementation(project(":core"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.work.runtime.ktx)

    // Hilt library only (no Hilt Gradle plugin / KSP in :scheduling): supplies the @Inject
    // and @ApplicationContext annotations. The adapter/use-case factories are generated by
    // :app's Hilt+KSP processor from these compiled @Inject constructors. See T-008 ADR on
    // minimal Hilt placement.
    implementation(libs.hilt.android)

    testImplementation(libs.junit4)
    testImplementation(libs.robolectric)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlinx.coroutines.test)
    androidTestImplementation(libs.junit.ext)
}

// Kover per-package coverage gate (ADR-078 deferral resolved at T-008). Kover 0.8.x forbids
// per-rule filters, so the report-wide filter scopes both the report and the verify gate to
// the Application layer only: io.nemopill.scheduling.application.* >= 80% line. As a
// consequence, infrastructure.* and presentation.* are excluded from this module's coverage
// report entirely (not just un-gated) — they carry no % threshold and are exercised by the
// Robolectric integration test. Recorded as a T-008 ADR.
kover {
    reports {
        filters {
            includes {
                classes("io.nemopill.scheduling.application.*")
            }
        }
        verify {
            rule("io.nemopill.scheduling.application line coverage >= 80%") {
                bound {
                    minValue = 80
                }
            }
        }
    }
}
